card_image: ''
created_at: 2025-03-25 18:52:23.613000
creator_id: unknown
deployment:
  last_deployed: null
  type: null
  url: ''
description: Notes application with Supabase Auth and Database integration
domain: ''
features:
- ''
getting_started_screen: false
getting_started_screen_index: 0
git:
  branch: main
  remote: origin
  url: https://github.com/memextech/supabase-app
hero_image: ''
icon: ''
is_published: true
pills:
- icon: ''
  label: ''
  prompt: ''
project_id: lLWvSv4P41IhX8CXFyAN
published_at: 2025-03-25 18:52:37.215000
requirements:
- description: ''
  type: ''
slug: ''
storage:
  compression_enabled: null
  gcs_path: null
  last_sync: null
  max_file_size_mb: null
  size_bytes: null
title: SupabaseNotes application
tools:
- name: ''
  role: ''
  type: ''
  version: ''
updated_at: 2025-03-25 18:52:37.215000
